### ISSUE TITLE
Missing 32-bit libz.so

### ISSUE THREAD

**Issue by dsblank** [jsoftware/jupyter#1]
Attempting running new download (as advertised in Jupyter mailing list) on Ubuntu 16.10.

```shell
$ ./jupyter-notebook.sh 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/dblank/Desktop/JDemo/Python3/lib/python3.6/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/home/dblank/Desktop/JDemo/Python3/lib/python3.6/site-packages/notebook/nbextensions.py", line 13, in <module>
    import zipfile
  File "/home/dblank/Desktop/JDemo/Python3/lib/python3.6/zipfile.py", line 15, in <module>
    import binascii
ImportError: libz.so.1: cannot open shared object file: No such file or directory
```
I tried including existing folders containing libz.so.1 but was wrong ELF class. Tried commenting out the import zipfile, but then:

```
ModuleNotFoundError: No module named 'urlparse'
```

**Comment by martin-saurer** [comment]
Could this be a 32/64-bit mismatch?
Is your Ubuntu 16.10 a 64-bit system?
Do you have a chance installing 32-bit libraries?

Best

Martin

**Comment by dsblank** [comment]
Yes, it is a 64-bit system.

I was just giving you feedback. As you can see (and perhaps know), getting an all-in-one download can be tricky, which is why most groups go with standard installation tools, such as pip, or a big project, like anaconda.

**Comment by martin-saurer** [comment]
Thanks for the feedback.

Yes, I know, battery-included environments can be tricky.

But our goal was to create environments that do not contain the full-blown anaconda environment,
and the people who download it should not have to deal with pip commands etc.

The manual installation into an existing environment is still possible.
Please see: https://github.com/martin-saurer/jkernel <https://github.com/martin-saurer/jkernel>

Best

Martin
